version: "3.9"
services:
  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "3001:3001"
    depends_on:
      - backend
  backend:
    build: ./backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      JWT_SECRET: xpto12345
      MONGO_URI: mongodb://root:example@mongo:27017
    depends_on:
      - mongo
  backend-test:
    build: ./backend
    command: ["npm", "test"]
    volumes:
      - ./backend/__tests__:/app/__tests__
    environment:
      JWT_SECRET: xpto12345
      MONGO_URI: mongodb://root:example@mongo:27017
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
